#!/usr/bin/env sh
# Auto-generated by EveSession. Prefer using Eve to persist cd/export changes.
# shellcheck shell=sh
export VIRTUAL_ENV=/Users/liyuzerihun/eve/venv
export PATH="$VIRTUAL_ENV/bin:$PATH"
cd /Users/liyuzerihun/eve
